### ISSUE TITLE
"Unexpected token" error

### ISSUE THREAD

**Issue by ahartz1** [indutny/hash.js#23]
I just upgraded from 1.1.5 to 1.1.6 and now get the following error when running UglifyJs:

`Unexpected token: name (p) [./node_modules/hash.js/lib/hash/utils.js:30,0]`

**Comment by fanatid** [comment]
https://github.com/indutny/hash.js/pull/22#issuecomment-443271311

Maybe because `let`? https://github.com/indutny/hash.js/pull/22/files#diff-747fe63b74f9b055d75a36bd049af415R30

**Comment by indutny** [comment]
Should be fixed in 1.1.7, sorry!

**Comment by ahartz1** [comment]
Awesome, thanks so much!
