### ISSUE TITLE
Windows Defender tagging lib/hash/sha.js as Trojan:Win32/Vigorf.A

### ISSUE THREAD

**Issue by garrettloy** [indutny/hash.js#7]
I found this when installing browserify globally using "npm install -g browserify"- windows defender perks up and flags this file while in npm's staging folder, then in the module folder for hash.js after npm does its thing and moves everything from staging.

I subsequently tried installing hash.js globally (npm instal -g hash.js) and windows defender flagged the same file as that trojan.

I then tried downloading just the sha.js file, right clicking "scan with windows defender" and it flagged the file as that trojan.

Putting the file through virus total yields nothing, **believed to be false positive.**

Windows Defender definition: 1.239.1256.0

**Comment by CoolMatty** [comment]
Just commenting to say I also was hit by this, running defender definitions: 1.239.1273.0, same file.

**Comment by indutny** [comment]
Not sure if this is actionable. If you'll check the contents of the file - it is just a plain JavaScript file without any viruses :D

**Comment by garrettloy** [comment]
Yeah not sure what to do about it either, obviously just raw javascript. Thought I'd bring it to your attention though!

**Comment by indutny** [comment]
Thanks!

**Comment by third774** [comment]
I, too, am running into this.

**Comment by jesstelford** [comment]
Just for SEO goodness; We too hit this issue on Windows thinking `sha.js` was Vigorf.A.

For those concerned; [this is the file](https://github.com/indutny/hash.js/blob/master/lib/hash/sha.js), which was last updated 2 years ago... Pretty safe IMHO.

**Comment by jeffwilcox** [comment]
+1 sigh impacting a bunch of stuff at the moment

**Comment by rmegal** [comment]
I was experiencing this problem yesterday so I opened an issue with MMPC support. Their reply is that this is fixed in the latest signature files. I updated Defender and this no longer occurs.
